version: '3.8'

services:
  # Laravel App
  laravel:
    build:
      context: ./LaravelAPI
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: unless-stopped
    volumes:
      - ./LaravelAPI:/var/www
    depends_on:
      - mysql
      - redis
      - rabbitmq

  # Laravel Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./LaravelAPI:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  # Node.js Microservice
  nodejs:
    build:
      context: ./NodeJsMicroService
      dockerfile: Dockerfile
    container_name: node_microservice
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: ./NodeJSMicroservice/.env
    volumes:
    - ./NodeJSMicroservice:/usr/src/app
    depends_on:
      - mysql
      - redis
      - rabbitmq

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis Server
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  laravel-migrate:
    build:
      context: ./LaravelAPI
    depends_on:
      - mysql
    command: bash -c "php artisan migrate --force"

volumes:
  mysql_data:
